import { toast } from "sonner";

/**
 * Registers the service worker generated by vite-plugin-pwa.
 *
 * Production only — in dev mode the plugin is disabled, and we also guard with
 * import.meta.env.PROD so we never ship a SW during `vite dev`.
 *
 * UX:
 *  - onOfflineReady → info toast: "App pronto para uso offline"
 *  - onNeedRefresh  → action toast: "Nova versão disponível" with a button
 *    that calls updateSW(true) (skipWaiting + reload). Debounced — we only
 *    show one toast per session until dismissed/confirmed.
 */
export async function registerPWA(): Promise<void> {
  if (!import.meta.env.PROD) return;
  if (typeof window === "undefined") return;
  if (!("serviceWorker" in navigator)) return;

  try {
    const { registerSW } = await import("virtual:pwa-register");

    let updatePromptShown = false;

    const updateSW = registerSW({
      immediate: true,
      onOfflineReady() {
        toast.success("App pronto para uso offline", {
          description: "Agora você pode acessar o DRE Control sem internet.",
          duration: 5000,
        });
      },
      onNeedRefresh() {
        if (updatePromptShown) return;
        updatePromptShown = true;

        toast("Nova versão disponível", {
          description: "Clique em atualizar para recarregar com as últimas melhorias.",
          duration: Infinity,
          action: {
            label: "Atualizar",
            onClick: () => {
              toast.loading("Nova versão disponível — recarregando...", {
                duration: 3000,
              });
              // Trigger skipWaiting + reload via vite-plugin-pwa
              void updateSW(true);
            },
          },
          onDismiss: () => {
            // Allow re-prompting later (e.g., next SW check) if user dismisses.
            updatePromptShown = false;
          },
        });
      },
      onRegisterError(error) {
        // Non-fatal: log but don't crash the app.
        console.error("[PWA] Service worker registration failed:", error);
      },
    });
  } catch (error) {
    console.error("[PWA] Failed to load registration module:", error);
  }
}
